---

- include: apt-key.yml
  until: result.rc == 0
  retries: 10

- name: Add Mesosphere repo
  apt_repository:
    repo: "{{ mesosphere_apt_repo }}"
    state: present
    update_cache: yes

- name: Install Debian OS packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - "{{ mesos_apt_package }}"
