---

- name: create mesos agent entries for syslogd
  become: yes
  copy:
    dest: /etc/rsyslog.d/21-mesos-agent.conf
    content: |
      # Mesos logging
      :syslogtag, isequal, "mesos-slave:"  /var/log/mesos/mesos-agent.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - mesos

- meta: flush_handlers

- include: upstart-follower-init.yml
  when: ansible_service_mgr != 'systemd'

- include: systemd-follower-init.yml
  when: ansible_service_mgr == 'systemd'

- meta: flush_handlers

- name: Restart mesos agent
  service: name=mesos-slave state=restarted enabled=yes
  tags: deploy

- name: Ensure that mesos agent has started and keeps running
  service: name=mesos-slave state=started
  tags: deploy
  register: mesos_slave_running
  until: mesos_slave_running.state == 'started' and not mesos_slave_running|changed
  retries: 2
  delay: 5

- name: Validate that mesos agent is running
  fail:
    msg: >
      Service mesos-slave has not started as expected, please check its current status or error messages
  when: mesos_slave_running.state != 'started' or mesos_slave_running|changed
  tags: deploy
