---

- name: create mesos entries for syslogd
  become: yes
  copy:
    dest: /etc/rsyslog.d/20-mesos-master.conf
    content: |
      # Mesos logging
      :syslogtag, isequal, "mesos-master:"  /var/log/mesos/mesos-master.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - mesos

- meta: flush_handlers

- include_tasks: upstart-leader-init.yml
  when: ansible_service_mgr != 'systemd'

- include_tasks: systemd-leader-init.yml
  when: ansible_service_mgr == 'systemd'

- meta: flush_handlers

- name: Start Mesos master
  service: name=mesos-master state=started enabled=yes
  tags: deploy

- name: Ensure that Mesos master has started and keeps running
  service: name=mesos-master state=started
  tags: deploy
  register: mesos_master_running
  until: mesos_master_running.state == 'started' and not mesos_master_running is changed
  retries: 2
  delay: 5

- name: Validate that Mesos master is running
  fail:
    msg: >
      Service mesos-master has not started as expected, please check its current status or error messages
  when: mesos_master_running.state != 'started' or mesos_master_running is changed
  tags: deploy
