---

- name: create mesos entries for syslogd
  become: yes
  copy:
    dest: /etc/rsyslog.d/20-mesos-master.conf
    content: |
      # Mesos logging
      :syslogtag, isequal, "mesos-master:"  /var/log/mesos/mesos-master.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - mesos

- meta: flush_handlers

- include: upstart-leader-init.yml
  when: ansible_service_mgr != 'systemd'

- include: systemd-leader-init.yml
  when: ansible_service_mgr == 'systemd'
