---
# Here we are using the debian package if debian
- include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: common.yml
  tags:
    - mesos

# Here we are using the debian package if debian
- import_tasks: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - mesos
    - bootstrap

- import_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - mesos
    - bootstrap

- import_tasks: mesos.yml
  tags:
    - mesos

- import_tasks: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"
  tags:
    - mesos

- import_tasks: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
  tags:
    - mesos

- meta: flush_handlers
  tags:
    - mesos
