---
# Here we are using the debian package if debian
- include_vars: "{{ ansible_os_family }}.yml"

- include: common.yml
  tags:
    - mesos

# Here we are using the debian package if debian
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - mesos
    - bootstrap

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - mesos
    - bootstrap

- include: mesos.yml
  tags:
    - mesos

- include: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"
  tags:
    - mesos

- include: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
  tags:
    - mesos

- meta: flush_handlers
  tags:
    - mesos
