---

# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

- include_tasks: upstart-init.yml
  when: ansible_service_mgr != 'systemd'

- include_tasks: systemd-init.yml
  when: ansible_service_mgr == 'systemd'

- name: Disable mesos leader
  become: yes
  service:
    name: mesos-master
    enabled: no
  when: mesos_mode == "follower"
  tags:
    - mesos

- name: Disable mesos follower
  become: yes
  service:
    name: mesos-slave
    enabled: no
  when: mesos_mode == "leader"
  tags:
    - mesos
