---

- name: Check if upstart exists
  stat: path=/etc/init/
  register: etc_init

- name: Check if systemd exists
  stat: path=/etc/systemd/system/
  register: systemd_check

# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

# == Configure and recreate
- name: Init config -- Mesos default config file
  template: src=defaults.j2 dest=/etc/default/mesos
  when: etc_init.stat.exists == true and systemd_check.stat.exists == false
  notify:
    - restart mesos leader
    - restart mesos follower

- name: Init config -- Configure /etc/mesos/zk
  become: yes
  copy:
    content: "{{ mesos_zk }}"
    dest: /etc/mesos/zk
  when: etc_init.stat.exists == true and systemd_check.stat.exists == false
  tags:
    - mesos

- name: Init config -- Configure /etc/mesos/hostname
  become: yes
  copy:
    content: "{{ inventory_hostname }}"
    dest: /etc/mesos/hostname
    mode: 0600
  when: etc_init.stat.exists == true and systemd_check.stat.exists == false
  tags:
    - mesos

- name: Disable mesos leader
  become: yes
  service:
    name: mesos-master
    enabled: no
  when: mesos_mode == "follower"
  tags:
    - mesos

- name: Disable mesos follower
  become: yes
  service:
    name: mesos-slave
    enabled: no
  when: mesos_mode == "leader"
  tags:
    - mesos

- name: Init config -- Delete /etc/mesos - replaced by systemd config
  become: yes
  when: systemd_check.stat.exists == true
  file:
    dest: /etc/mesos
    state: absent
  tags:
    - mesos
