---

- name: cleanup upstart configuration
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/mesos-slave
    - /etc/mesos-slave
    - /etc/init/mesos-slave.conf
  notify:
    - restart mesos follower

- name: install mesos-slave unit file
  become: yes
  template:
    src: mesos-slave.service.j2
    dest: /etc/systemd/system/mesos-slave.service
  notify:
    - reload unit files
    - restart mesos follower
  tags:
    - bootstrap

- name: create sysconfig folder
  become: yes
  file:
    path: /etc/sysconfig
    state: directory

- name: configure mesos-agent
  become: yes
  template:
    src: mesos-agent.sysconfig.j2
    dest: /etc/sysconfig/mesos-agent
  notify: remove mesos follower metadata

- name: write credential
  when: do_mesos_follower_auth|bool
  become: yes
  copy:
    dest: /etc/sysconfig/mesos-agent-credential
    content: "{{ mesos_follower_principal }} {{ mesos_follower_secret }}"
    mode: 0600
  notify: restart mesos follower

- name: delete credential
  when: not do_mesos_follower_auth|bool
  become: yes
  file:
    dest: /etc/sysconfig/mesos-agent-credential
    state: absent
  notify: restart mesos follower

- name: Restart Mesos agent on boot using systemd
  command: systemctl enable mesos-slave
  args:
    creates: /lib/systemd/system/mesos-slave.service
