---
- name: reload unit files
  become: yes
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

# i.e. upgrade mesos, templates stay the same...
- name: restart mesos leader
  service: name=mesos-master state=restarted
  when: mesos_mode == "leader" or mesos_mode == "mixed"
  become: yes

- name: remove mesos follower metadata
  become: yes
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - service mesos-slave stop
    - "rm -rf  {{ mesos_work_dir }}/mesos/meta/slaves/latest"
    - service mesos-slave stop

- name: restart mesos follower
  service: name=mesos-slave state=restarted
  when: mesos_mode == "follower" or mesos_mode == "mixed"
  become: yes
